name: shrifashion
description: A new Flutter application.
publish_to:
version: 1.0.1+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fdottedline: ^1.0.1
  url_launcher: ^6.0.4
  flutter_share: ^2.0.0
  sticky_headers: ^0.2.0
  path_provider: ^1.6.28
  firebase_dynamic_links: ^0.5.1

  mailer: ^2.0.2
  flutter_icons: ^1.1.0
  connectivity: ^2.0.2
  carousel_pro: ^1.0.0
  fluttertoast: ^7.1.1
  cupertino_icons: ^0.1.3
  razorpay_flutter:
    git:
      url: git://github.com/razorpay/razorpay-flutter.git
      ref: master

  toast: ^0.1.5
  html: ^0.14.0+4
  expandable: ^4.1.4
  animated_dialog_box:
  carousel_slider: ^2.3.1
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.1.6
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.0.8

  http:

  flutter_spinkit: ^4.1.2
  hexcolor: ^1.0.6
  shared_preferences: ^0.5.12+4
  pin_entry_text_field: ^0.1.4
  pin_code_text_field: ^1.7.1
  permission_handler: ^3.1.0
  firebase_messaging: ^6.0.16



  google_maps_flutter: ^1.0.3

  location: ^2.3.5
  charts_flutter: ^0.6.0
  geolocator: ^6.1.1
  geocoder: ^0.2.1
  flutter_share_me: ^0.9.2


  video_player: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0



flutter:
  uses-material-design: true

  assets:
    - images/
    - images/OTPverified.png
    - images/veg_green.webp
    - images/why.jpg
    - images/bike.jpg
    - images/Empty.jpeg
    - images/Empty.jpg
    - images/Arrow.png
    - images/percentage.jpeg
    - images/CouponSuccess.png
    - images/Tick.jpeg
    - images/male_user.jpeg
    - images/female_user.jpeg
    - images/veg_logo1.jpeg
    - images/veg_logo2.jpeg
    - images/veg_logo3.jpeg
    - images/OrderComplete2.jpeg
    - images/shri_display.jpeg
    - images/Shrisolutions.mp4
    - images/offers.jpeg
    - images/launcher.jpeg
    - images/bike.jpg
    - images/Logo.png
  fonts:
    - family: Fredoka One
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
        - asset: fonts/SourceSansPro-Regular.ttf

